/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:455ee0d9-82b9-4e61-bf8e-a9f39540e30b",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_plXzAdlHa",
    "aws_user_pools_web_client_id": "2va5729ehfj97clm8l1s3ms888",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hlew6jnsczgqbede4ntbmrcnue.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-47enftpfqjggvc6wpqjldcjfre",
    "aws_user_files_s3_bucket": "k231062400-staging",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
