/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:455ee0d9-82b9-4e61-bf8e-a9f39540e30b",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_plXzAdlHa",
    "aws_user_pools_web_client_id": "2va5729ehfj97clm8l1s3ms888",
    "oauth": {}
};


export default awsmobile;
